### PR TITLE
Updating deprecated method boldTextOverride

### PR DESCRIPTION
**Pull request by Simonpiro**

### CODE REVIEW

**Comment by kunal-mansukhani** [comment]
can someone merge this pls

**Comment by IvanGast** [comment]
Yes, merge please.

**Comment by ameyanaik11** [comment]
I confirmed the fix worked locally on my project.

**Comment by ChunhThanhDe** [comment]
### Issue Description

The following error occurs when trying to compile the application:

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_glow-0.3.0/lib/src/widget/glow_text.dart:79:20: Error: Member not found: 'MediaQuery.boldTextOverride'.
    if (MediaQuery.boldTextOverride(context)) {
                   ^^^^^^^^^^^^^^^^
Failed to compile application.
```

### Solution

To fix this issue, replace `MediaQuery.boldTextOverride` with `MediaQuery.boldTextOf`.

#### Original Code:
```dart
if (MediaQuery.boldTextOverride(context)) {
```

#### Updated Code:
```dart
if (MediaQuery.boldTextOf(context)) {
```

I have verified this patch, and I confirm that it is valid. Please integrate this patch. @AmirJabbari 

---

**Review by AmirJabbari — APPROVED** [review]

**Comment by ataberkw** [comment]
pubspec.yaml > dependencies
```
  flutter_glow:
    git:
      url: https://github.com/Simonpiro/flutter-glow
      ref: patch-1
```

Till the merge merged

**Pull request merged**
